Repository uu-haunter/busplus, pull requests merged in 2021-05, with the labels that each got.

#60 Seat reservation/unreservation and continuous geo-pos updates
  client/public/circle.svg
  client/src/SearchBar.js
  client/src/map.js
Labels: feature

#61 Feature/client smooth rotation
  client/public/small_simple_bus.svg
  client/src/App.js
  client/src/SearchBar.js
  client/src/map.js
  client/src/messages.js
Labels: enhancement, feature

#59 Added Reserve/Unreserve seat and error messages
  protocol-documentation.md
  server/src/client.rs
  server/src/database.rs
  server/src/lobby.rs
  server/src/messages.rs
  server/src/protocol/client_protocol.rs
  server/src/protocol/server_protocol.rs
  server/src/ws.rs
Labels: enhancement, feature

#62 Line number in vehicle positions
  server/src/lobby.rs
  server/src/messages.rs
  server/src/protocol/server_protocol.rs
Labels: feature

#63 Fixed protocol and reserve seat bug
  client/src/messages.js
  protocol-documentation.md
Labels: bug

#67 Feature/server passenger information update
  protocol-documentation.md
  server/Cargo.toml
  server/src/client.rs
  server/src/gtfs/trafiklab.rs
  server/src/lobby.rs
  server/src/messages.rs
  server/src/protocol/client_protocol.rs
  server/src/protocol/server_protocol.rs
  server/src/util.rs
  server/src/ws.rs
Labels: enhancement, feature

#70 Can now query for shapes with trip_id & line number
  protocol-documentation.md
  server/src/lobby.rs
  server/src/messages.rs
  server/src/protocol/client_protocol.rs
  server/src/protocol/server_protocol.rs
  server/src/util.rs
  server/src/ws.rs
Labels: enhancement

#73 No realtime request is made when no clients are connected.
  server/src/lobby.rs
Labels: fix

#72 Added necessary information about running the app in the future.
  README.md
Labels: enhancement
