Repository uu-haunter/busplus, pull requests merged in 2021-04, with the labels that each got.

#32 Utility for parsing Trafiklab static data.
  README.md
  server/Cargo.toml
  server/src/config.rs
  server/src/gtfs/mod.rs
  server/src/gtfs/trafiklab.rs
  server/src/gtfs/transit_static.rs
  server/src/lobby.rs
  server/src/main.rs
  server/src/ws.rs
Labels: feature

#44 MongoDB synchronous & "get-route-info" message.
  protocol-documentation.md
  server/Cargo.toml
  server/src/database.rs
  server/src/gtfs/transit_static.rs
  server/src/lobby.rs
  server/src/main.rs
  server/src/messages.rs
  server/src/protocol/server_protocol.rs
  server/src/ws.rs
Labels: feature

#49 Moved echo interval to the config file
  README.md
  server/src/config.rs
  server/src/lobby.rs
Labels: enhancement

#50 Personpin features
  client/public/circle.svg
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/map.js
Labels: enhancement

#52 Async mongodb communication and async get route info handler.
  server/Cargo.toml
  server/src/database.rs
  server/src/lobby.rs
  server/src/main.rs
  server/src/ws.rs
Labels: enhancement, feature

#53 Search bar is now functional, pulsating position pin now works
  client/src/App.js
  client/src/SearchBar.js
  client/src/map.js
Labels: enhancement, feature

#54 Loading screen for first Trafiklab API request
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/LoadingScreen.css
  client/src/LoadingScreen.js
  client/src/map.js
Labels: enhancement, feature
